# Generated by Django 3.2.25 on 2025-06-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publicacion_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='hora_creacion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='titulo',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='categoria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='defensas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='nombre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='pais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='record',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='titulos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
