# Generated by Django 3.2.25 on 2025-06-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_publicacion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='altura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='apodo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
