# Generated by Django 3.2.25 on 2025-06-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20250621_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='defensas',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='peso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
