# Generated by Django 3.2.25 on 2025-06-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20250621_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
