# Generated by Django 3.2.25 on 2025-06-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_publicacion_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='video_url',
        ),
    ]
